# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [ ]:
# Import NumPy as its abbreviation 'np'


In [ ]:
# Create a 1-dimensional NumPy array using np.array()
import numpy as np
data1 = [1, 2, 3, 4]
arr1 = np.array(data1)
print("1d array", arr1)
# Create a 2-dimensional NumPy array using np.array()
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print("2d array: ",arr2)
# Create a 3-dimensional Numpy array using np.array()
data3 = [[1, 2, 3, 4], [5, 6, 7, 8],[9, 3, 4, 5]]
arr3 = np.array(data3)
print("3d array: ", arr3)

1d array [1 2 3 4]
2d array:  [[1 2 3 4]
 [5 6 7 8]]
3d array:  [[1 2 3 4]
 [5 6 7 8]
 [9 3 4 5]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print("Type:",type(arr1)) # Type: <class 'numpy.ndarray'>
print("Shape:", arr1.shape) # Shape: (6,)
print("Size:",arr1.size) # Size: 6
print("Dimensions:", arr1.ndim) # Dimensions: 1
print("Data type:", arr1.dtype) # Data type: int64
print("Item_Size:",arr1.itemsize) # size in bytes of each element of the array.
print("total_memory: =", arr1.size * arr1.itemsize,"bytes")

Type: <class 'numpy.ndarray'>
Shape: (4,)
Size: 4
Dimensions: 1
Data type: int64
Item_Size: 8
total_memory: = 32 bytes


In [ ]:
# Attributes of 2-dimensional array
print("Type:",type(arr2))
print("Shape:", arr2.shape)
print("Size:",arr2.size)
print("Dimensions:", arr2.ndim)
print("Data type:", arr2.dtype)
print("Item_Size:",arr2.itemsize)
print("total_memory: =", arr2.size * arr2.itemsize,"bytes")

Type: <class 'numpy.ndarray'>
Shape: (2, 4)
Size: 8
Dimensions: 2
Data type: int64
Item_Size: 8
total_memory: = 64 bytes


In [ ]:
# Attributes of 3-dimensional array
print("Type:",type(arr3))
print("Shape:", arr3.shape)
print("Size:",arr3.size)
print("Dimensions:", arr3.ndim)
print("Data type:", arr3.dtype)
print("Item_Size:",arr3.itemsize)
print("total_memory: =", arr3.size * arr3.itemsize,"bytes")

Type: <class 'numpy.ndarray'>
Shape: (3, 4)
Size: 12
Dimensions: 2
Data type: int64
Item_Size: 8
total_memory: = 96 bytes


In [ ]:
# Create an array of shape (10, 2) with only ones
import numpy as np
array = np.ones((10, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
import numpy as np
array=np.zeros((7,2,3))
print(array)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
# Create an array within a range of 0 and 100 with step 3
import numpy as np

array = np.arange(0, 100, 3)
print(array)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
import numpy as np
array = np.random.randint(0, 11, (7, 2))
print(array)

[[ 1  3]
 [ 3  1]
 [ 1  9]
 [10 10]
 [ 0  4]
 [10  2]
 [ 9  6]]


In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
import numpy as np

array = np.random.rand(3, 5)  # Generates random floats between 0 and 1
print(array)

[[0.99001444 0.75723771 0.96530059 0.78903921 0.67384897]
 [0.93956167 0.76777244 0.09883862 0.08339441 0.50594262]
 [0.49755674 0.11185924 0.74374165 0.73514928 0.56441026]]


In [ ]:
# Set the random seed to 42
import numpy as np
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
array = np.random.randint(0, 11, (4, 6))
print(array)

[[ 6  3 10  7  4  6]
 [ 9  2  6 10 10  7]
 [ 4  3  7  7  2  5]
 [ 4  1  7  5  1  4]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
import numpy as np
random_array = np.random.randint(1, 11, size=(3, 7))
unique_nums = np.unique(random_array)
# Find the unique numbers in the array you just created
print("Random Array:\n", random_array)
print("Unique Numbers:", unique_nums)

Random Array:
 [[ 1 10  6  9  1 10  3]
 [ 7  4  9  3  5  3  7]
 [ 5  9  7  2  4  9  2]]
Unique Numbers: [ 1  2  3  4  5  6  7  9 10]


In [ ]:
# Find the 0'th index of the latest array you created
print(random_array[0])

[ 1 10  6  9  1 10  3]


In [ ]:
# Get the first 2 rows of latest array you created
two_rows = random_array[:2]
# Print the result
print("First 2 Rows of random_array:\n", two_rows)

First 2 Rows of random_array:
 [[ 1 10  6  9  1 10  3]
 [ 7  4  9  3  5  3  7]]


In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
values = random_array[:2, :2]
print("the first 2 values of first two rows: ", values)

the first 2 values of first two rows [[ 1 10]
 [ 7  4]]


In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
import numpy as np
random_array2 = np.random.randint(0, 11, size=(3, 5))
ones_array = np.ones((3, 5))

# Print results
print("Random Array:\n", random_array2)
print("Ones Array:\n", ones_array)

Random Array:
 [[9 8 9 4 1]
 [3 6 7 2 0]
 [3 1 7 3 1]]
Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Add the two arrays together
merged_array=random_array2+ones_array
print(merged_array)

[[10.  9. 10.  5.  2.]
 [ 4.  7.  8.  3.  1.]
 [ 4.  2.  8.  4.  2.]]


In [ ]:
# Create another array of ones of shape (5, 3)
ran_array = np.ones((5, 3))
print(ran_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Try add the array of ones and the other most recent array together
new_sum_array = ran_array + ones_array

# Print the result
print("New Sum of Arrays:\n", new_sum_array)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?
answer:  because NumPy's broadcasting rules require exactly matching shapes
How would you fix it?
transpose the array using .T

In [ ]:
# Create another array of ones of shape (3, 5)
onesarray_3x5 = np.ones((3, 5))
print("Ones Array of shape (3x5):\n", onesarray_3x5)

Ones Array of shape (3x5):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Subtract the new array of ones from the other most recent array
subtracted= ran_array.T-onesarray_3x5
print(subtracted)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Multiply the ones array with the latest array
multiplied_array = ran_array.T * onesarray_3x5
print("Multiplied Array: ", multiplied_array)

Multiplied Array:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Take the latest array to the power of 2 using '**'
power_array = onesarray_3x5 ** 2
print("Array to the power of 2: ", power_array)

Array to the power of 2:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Do the same thing with np.square()
square_array = np.square(onesarray_3x5)
print("sqaured array: ", square_array)

sqaured array:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Find the mean of the latest array using np.mean()
mean_value = np.mean(onesarray_3x5)
print(mean_value)

1.0


In [ ]:
# Find the maximum of the latest array using np.max()
max_value = np.max(onesarray_3x5)
print("Maximum value:", max_value)

Maximum value: 1.0


In [ ]:
# Find the minimum of the latest array using np.min()
min_value=np.min(onesarray_3x5)
print(min_value)

1.0


In [ ]:
# Find the standard deviation of the latest array
std_dev = np.std(onesarray_3x5)
print("Standard Deviation:", std_dev)

Standard Deviation: 0.0


In [ ]:
# Find the variance of the latest array
variance = np.var(onesarray_3x5)
print("Variance:", variance)

Variance: 0.0


In [ ]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = onesarray_3x5.reshape(3, 5, 1)
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [ ]:
# Transpose the latest array
transposed_array = onesarray_3x5.T
print("Transposed Array:\n", transposed_array)


Transposed Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


What does the transpose do?
my answer: transpose operation swaps the rows and columns of that matrix

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1 = np.random.randint(0, 10, (3, 3))
array2 = np.random.randint(0, 10, (3, 2))
print("Array 1:  ", array1)
print("Array 2:  ", array2)

Array 1:   [[5 5 9]
 [3 5 1]
 [9 1 9]]
Array 2:   [[3 7]
 [6 8]
 [7 4]]


In [ ]:
# Perform a dot product on the two newest arrays you created
dot_product_1 = np.dot(array1, array2)
print("Dot Product of (3,3) and (3,2) arrays: ", dot_product_1)

Dot Product of (3,3) and (3,2) arrays:
 [[108 111]
 [ 46  65]
 [ 96 107]]


In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array3 = np.random.randint(0, 10, (4, 3))
array4 = np.random.randint(0, 10, (4, 3))
print("Array 3:  ", array3)
print("Array 4:  ", array4)

In [ ]:
# Perform a dot product on the two newest arrays you created
dot_product_2 = np.dot(array3, array4)
print("dot product: ",dot_product_2)

NameError: name 'array3' is not defined

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
array3 = np.random.randint(0, 10, (4, 3))
array4 = np.random.randint(0, 10, (4, 3))
dot_product = np.dot(array3, array4.T)
print("Dot Product : ", dot_product)

Dot Product :  [[ 49  42  30  96]
 [135  72  50 201]
 [ 68  68  24 102]
 [105  49  16 114]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1 = np.random.randint(0, 10, (3, 3))
array2 = np.random.randint(0, 10, (3, 3))

print("Array 1: ", array1)
print("Array 2: ", array2)

Array 1:  [[8 6 8]
 [7 1 0]
 [6 6 7]]
Array 2:  [[4 2 7]
 [5 2 0]
 [2 4 2]]


In [ ]:
# Compare the two arrays with '>'
compare = array1 > array2
print("Array1 > Array2: ", compare)

Array1 > Array2:  [[ True  True  True]
 [ True False False]
 [ True  True  True]]


What happens when you compare the arrays with `>`?

answer: It returns a boolean values.


In [ ]:
# Compare the two arrays with '>='
compare2 = array1 >= array2
print("Array1 >= Array2:  ", compare2)

Array1 >= Array2:   [[ True  True  True]
 [ True False  True]
 [ True  True  True]]


In [ ]:
# Find which elements of the first array are greater than 7
greater_than_7 = array1 > 7
print("Elements in Array1 greater than 7: ", greater_than_7)

Elements in Array1 greater than 7:  [[ True False  True]
 [False False False]
 [False False False]]


In [ ]:
# Which parts of each array are equal? (try using '==')
is_equal = array1 == array2
print("Equal elements in Array1 and Array2:  ", is_equal)

Equal elements in Array1 and Array2:   [[False False False]
 [False False  True]
 [False False False]]


In [ ]:
# Sort one of the arrays you just created in ascending order
sorted_array1 = np.sort(array1)
print("Sorted Array1 in ascending order:", sorted_array1)

Sorted Array1 in ascending order:
 [[6 8 8]
 [0 1 7]
 [6 6 7]]


In [ ]:
# Sort the indexes of one of the arrays you just created
sorted_indexes = np.argsort(array1)
print("Sorted indexes of Array1:", sorted_indexes)

Sorted indexes of Array1:
 [[1 0 2]
 [2 1 0]
 [0 1 2]]


In [ ]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(array1)
print("Index of maximum value in Array1:", max_index)

Index of maximum value in Array1: 0


In [ ]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(array1)
print("Index of minimum value in Array1:", min_index)

Index of minimum value in Array1: 5


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indices_axis1 = np.argmax(array1, axis=1)
print("Indexes of max values along axis 1:\n", max_indices_axis1)

Indexes of max values along axis 1:
 [0 0 2]


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indices_axis0 = np.argmin(array1, axis=0)
print("Indexes of min values along axis 0: ", min_indices_axis0)


Indexes of min values along axis 0:  [2 1 1]


In [ ]:
# Create an array of normally distributed random numbers
arrayn = np.random.randn(5)  # Generates 5 normally distributed numbers
print("Normally distributed: ", arrayn)

Normally distributed:  [ 0.36139561  1.53803657 -0.03582604  1.56464366 -2.6197451 ]


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arraym = np.linspace(1, 100, 10)
print("Evenly spaced numbers between 1 and 100: ", arraym)

Evenly spaced numbers between 1 and 100:
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

What happens when you try to broadcast a (3,) array with a (4,) array?

Explain why this operation might fail and how to fix it.
my explanantion to fix this:
in below code, the last dimension of the 1D array (3,) matches the last dimension of the 2D array (2,3), NumPy automatically broadcasts the operation row-wise.


Broadcasting in NumPy require that the shapes of the arrays must be Equal dimensions/shapes

In [ ]:
# code here

import numpy as np
#shape (2,3)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
#shape (3,)
array_1d = np.array([7, 5, 4])
result = array_2d + array_1d
print("Result of adding 1D array to 2D array:\n", result)

Result of adding 1D array to 2D array:
 [[ 8  7  7]
 [11 10 10]]


Write a NumPy program to add a 1D array of shape (3,) to a 2D array of shape (2, 3).


In [ ]:
#
array2 = np.random.randint((2,3))
array1 = np.random.randint((3,))
result = array2 + array1
print(array1)
print(array2)
print("Result:\n", result)

[1]
[1 0]
Result:
 [2 1]


Add a 1D array [10, 20, 30] to each row of a 2D array [[1, 2, 3], [4, 5, 6], [7, 8, 9]].

In [ ]:
import numpy as np
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_1d = np.array([10, 20, 30])
result = array_2d + array_1d
print("Result: ", result)

Result:  [[11 22 33]
 [14 25 36]
 [17 28 39]]


Attempt to add a 1D array [10, 20] to a 2D array [[1, 2, 3], [4, 5, 6]]. Explain the error.

In [ ]:
import numpy as np
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20])
result = array_2d + array_1d
print("Result: ", result)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

The 2D array has a shape of (2,3) and the 1D array has a shape of (2,)
broadcasting is not possible because the shapes/dimensions are not equal.

also, Since [10, 20]  has only 2 elements, NumPy cannot figure out how to expand it properly, causing a ValueError.

Multiply a 2D array [[1, 2], [3, 4]] with a 1D array [10, 20] using broadcasting.

In [ ]:
import numpy as np
array_2d = np.array([[1, 2], [3, 4]])
array_1d = np.array([10, 20])
result = array_2d * array_1d
print("Result: ", result)


Result:  [[10 40]
 [30 80]]
